export declare const TEMPLATE_VERSION = "8.0.0";
export declare const PIPELINE_MODE = "balanced_v8";
export { buildMoodboardScopeBlock, buildRenovationAnchorsBlock, V5_MOODBOARD_INFLUENCE_STATEMENT, INFLUENCE_PRESET_STYLE_ONLY, INJECTED_ITEM_BLOCK_HEADER, DEFAULT_USER_REQUEST, } from '../shared/canonicalPromptPrimitives.js';
export { buildAGTConstraintBlock } from '../blocks/agt-constraint.js';
export { buildAGTEchoBlock } from '../blocks/agt-echo.js';
export { buildConflictClausesBlock } from '../blocks/conflict-clauses.js';
export declare const BALANCED_V8_STRUCTURAL_PART = "**RENOVATION VISUALIZATION \u2014 INSTALLER BRIEF**\n\nYou are a professional renovation installer generating a photorealistic visualization for a client.\n\nYOUR TASK: Show the client exactly how their room will look after the selected products are installed. This is an accurate visual preview of a real renovation \u2014 not a stylistic redesign or concept render. The catalogue products listed in the Installed Products section are the actual items being installed. They define what must appear in this render.\n\nCATALOGUE-FIRST PRINCIPLE: All installed product specifications take absolute precedence over every other design decision. Style direction, material palette, and aesthetic choices are subordinate to and must not conflict with the installed products.\n\nPRESERVE ARCHITECTURE \u2014 DO NOT change:\n- Walls, floor plane, and ceiling plane\n- Window and door count, geometry, positions, and sizes\n- Camera angle, focal length, and perspective\n- Room proportions and spatial depth\n- Built-in light fixtures and structural niches\n\nPHOTOREALISM REQUIRED: The output must look like a real photograph of the finished renovation \u2014 not an illustration or concept sketch.\n\nARTIFACT REMOVAL: Remove exposed cables, loose wires, and temporary clutter. Replace with clean surfaces.\n\nWINDOW PRESERVATION: All window geometry is immutable \u2014 size, shape, position, pane count, and frame divisions. Do not add panes, arches, or new openings. Preserve the exterior view exactly as seen through any windows.";
export declare const buildV8StylePart: (styleName: string | null | undefined, roomType: string, userRequest: string) => string;
export declare const buildConstraintHierarchyBlock: (injectedItemCount: number, hasRenovationAnchors?: boolean, hasHardAGTFacts?: boolean) => string;
//# sourceMappingURL=visualization.constants.d.ts.map